version: '3.7'
services:
    atf-runner:
        build: ./
        image: atf-runner
        init: true
        restart: always
        environment:
            - NODE_ENV=production
        env_file:
            - .env
        container_name: atf-runner-${SN_INSTANCE_NAME}